### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by offlinehacker** [xtruder/nix-devcontainer#1]
- check spelling
- add description how it works
- add additional instructions how to use this template
- information about dotfiles

**Comment by Rizary** [comment]
I want to add some suggestion if you don't mind:
1. how to update nix flake
2. multiple workspace

**Comment by offlinehacker** [comment]
Thank you for suggestions.

Regarding nix flakes, I have working setup and I will create a separate tagged docker image with nix with flakes support. I will also provide multiple example devcontainers.

What do you mean by multiple workspaces?

**Comment by Rizary** [comment]
I mean multiple root workspaces:
https://code.visualstudio.com/docs/editor/multi-root-workspaces

can't wait for nix flake because I'm in the middle of updating https://github.com/nix-community/todomvc-nix to have haskell, rust, and go. It will be very nice if I can have debian-nix-devcontainer in that repo.

**Comment by offlinehacker** [comment]
@Rizary I still need to update README, but here is example for devcontainer with flakes support now: https://github.com/xtruder/debian-nix-devcontainer/tree/main/examples/workspace-docker-compose-with-flakes

**Comment by offlinehacker** [comment]
I did major updates regarding examples and README. It should be now much more clear how to use this devcontainer. I will stsill leave this issue open, as I plan to do more improvements.

**Comment by offlinehacker** [comment]
Closing this issue, as documentation should be much better now.
