### ISSUE TITLE
why you install so many tools via apt?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [xtruder/nix-devcontainer#10]
https://github.com/xtruder/nix-devcontainer/blob/1e361690e920b94e69488a60adb63c91c79ba2ee/src/Dockerfile#L20

**Comment by dsyer** [comment]
I guess you could also use one of the "standard" base images from Microsoft (e.g. `mcr.microsoft.com/vscode/devcontainers/base:0-focal`). Probably all you need on top of that is `curl` and `xz-utils` to run the nix installer.

**Comment by dzmitry-lahoda** [comment]
I am in progress right now to do that. We had previos attempt, so nix installation is broken if install nix via nix into MS container.

**Comment by offlinehacker** [comment]
The thing is I am not too much fan of existing Microsoft images, because they have these custom shell scripts to bootstrap environment and plugins. I think we could have nice portable development containers if Microsoft put more effort, but looks like they did minimal to get job done.

**Comment by offlinehacker** [comment]
On the second thought, I am not really opposing official Microsoft images that much, so if we can simplify this devcontainer it would be great as well.

**Comment by dsyer** [comment]
I’m not sure it would simplify it much without sacrificing features, unless (as you say) the base images change a bit. I use the MSFT base images for my experiments because they get me to a nixable container in VSCode relatively quickly, but I don’t need all the extra features here. I was just suggesting it in case the OP wanted to roll their own container.

**Comment by dzmitry-lahoda** [comment]
ok, seems home-manager approach works. even docker-in-docker works. but only locally. remotely its sucks https://github.com/NixOS/nix/issues/6680

**Comment by dzmitry-lahoda** [comment]
this PR based on others works https://github.com/ComposableFi/composable/pull/1530

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/composable/blob/dz/byog-container/Dockerfile 

- so it is official MS based
- minimal apts
- pre baked (so docker file is one liner)
- flake baked
- home-manager baked
- at least Rust Analayzer works, not sure if we will need to Go code as in this repo to fix extensions, home there are more declarative ways?
- MS derived container features like docker in docker work
- it has some direnv, but not yet tried if it works or like
-

**Comment by offlinehacker** [comment]
@dzmitry-lahoda what do you think would be the best way to go forward, making official nix devcontainer image? I have few additional things included in this image like:

- extension preloader, that will make sure that [nix-env-selector](https://marketplace.visualstudio.com/items?itemName=arrterian.nix-env-selector) is loaded before other extensions (before https://github.com/microsoft/vscode/issues/57481 is implemented in vscode)
- dynamic environment reloading without rebuilding image

What I see is missing is:

- base it on official ms image like you did
- optional integration for home manager (as devcontainer extensions maybe)

You can use flakes with this nix-devcontainer as well. It's not straightforward, as you need to have `shell.nix` to load `flake.nix`. I was thinking to switch to `https://marketplace.visualstudio.com/items?itemName=mkhl.direnv` or integrate into `nix-env-selector` support for loading flakes directly.

**Comment by dzmitry-lahoda** [comment]
I think best is https://github.com/microsoft/vscode-dev-containers/issues/947#issuecomment-1232110735 - use containerTools with home-manager mounted nix with ability to override and add docker-in-docker as feature.  so idea that you already in nix shell when is starts. so really I want just `nix develop` on start or during build. which what `home-manager` does.  is that will eliminate need nix-env-selector load first?

> dynamic environment reloading without rebuilding image.

I do not know.  Likely it is good. So I will follow other way. I will install and play with nix-env and usual plugins manually. As I like it I will bake them.  I am not good in nix and vscode to reload these. So may be home manager can help? 

So you pick either invest into vscode or into nix. I prefer nix. Because I want to use Helix too and produce artifacts with Hydra.

I based my work on https://github.com/jmgilman/dev-container . 

Also you may read about official stance from MS about features around nix way vs MS way. Definitely I dislike MS way because it is NOT Composable and represents all 👿  why we pick nix first.

**Comment by Chuxel** [comment]
> I’m not sure it would simplify it much without sacrificing features, unless (as you say) the base images change a bit. I use the MSFT base images for my experiments because they get me to a nixable container in VSCode relatively quickly, but I don’t need all the extra features here. I was just suggesting it in case the OP wanted to roll their own container.

@dsyer What would you like to change about the image?

**Comment by dzmitry-lahoda** [comment]
yeah, and nix does not support windows. so if assume windows inheritance with features, than nix is no go.
